name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'  

    - name: Run tests
      run: |
        #Test


    - name: Install dependencies
      if: success()  # Only run if previous steps were successful
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  

    - name: Extract branch name
      id: extract_branch_name
      run: echo "BRANCH_NAME=$(echo ${{ github.ref }} | sed 's/refs\/heads\///')" >> $GITHUB_ENV

    - name: Run Deployer
      env:
        REPO_NAME: ${{ github.repository }}
        BRANCH_NAME: ${{ env.BRANCH_NAME }}
        SSH_KEY: ${{ secrets.AWS_SSH_PRIVATE_KEY }}
        INSTANCE_IP: ${{ secrets.AWS_INSTANCE_IP }} 
      run: |
        echo "$SSH_KEY" > aws_key.pem
        chmod 600 aws_key.pem
        ssh -i aws_key.pem ec2-user@$INSTANCE_IP "sudo python3 /FINALPROJECT/deployer.py $REPO_NAME $BRANCH_NAME"