default:
  ami_id: 'ami-0abcdef1234567890'          # Replace with your AMI ID
  instance_type: 't2.micro'                # Replace with your instance type
  key_name: 'sanber-key'                  # Replace with your key pair name
  security_group_id: 'sg-0abcd1234efgh5678'  # Replace with your security group ID
