name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  pull_request:
      types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'  

    - name: Run tests
      run: |
        #Test

    - name: Set Up Git
      if: success()
      run: |
        # Configure Git to use the GitHub token for authentication
        git config --global url."https://${{ secrets.GITHUB_TOKEN }}@github.com/".insteadOf "https://github.com/"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Get Repository URL and Branch
      id: get_repo_info
      run: |
          # Get PR info
          PR_NUMBER=${{ github.event.pull_request.number }}
          REPO_URL="https://github.com/${{ github.repository }}"
          BRANCH_NAME=${{ github.head_ref }}
          
          # Output variables
          echo "REPO_URL=$REPO_URL" >> $GITHUB_ENV
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

    - name: Run Deployer
      env:
        REPO_URL: ${{ env.REPO_URL }}
        BRANCH_NAME: ${{ env.BRANCH_NAME }}
        SSH_KEY: ${{ secrets.AWS_SSH_PRIVATE_KEY }}
        INSTANCE_IP: ${{ secrets.AWS_INSTANCE_IP }} 
      if: github.event_name == 'pull_request'
      run: |
        echo "$SSH_KEY" > aws_key.pem
        chmod 600 aws_key.pem
        ssh -i aws_key.pem ec2-user@$INSTANCE_IP "sudo python3 /FINALPROJECT/deployer.py $REPO_NAME $BRANCH_NAME"
